import { Component } from '@angular/core';

@Component({
  selector: 'product-list',
  standalone: false,
  templateUrl: './product-list.component.html',
  styleUrl: './product-list.component.css'
})
export class ProductListComponent {

  products = [
    {
      id: 1,
      name: "Classic White T-Shirt",
      brand: "BasicsCo",
      gender: "unisex",
      category: "T-Shirts",
      size: "M",
      color: "White",
      price: 19.99,
      is_in_inventory: true,
      items_left: 120,
      imageURL: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=500&q=80",
      slug: "classic-white-t-shirt",
      description: "A timeless white tee made from soft cotton, perfect for any casual look."
    },
    {
      id: 2,
      name: "Slim Fit Jeans",
      brand: "DenimPro",
      gender: "male",
      category: "Jeans",
      size: "32",
      color: "Dark Blue",
      price: 49.99,
      is_in_inventory: true,
      items_left: 55,
      imageURL: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=500&q=80",
      slug: "slim-fit-jeans",
      description: "Dark blue slim fit jeans offering a sleek silhouette with durable denim fabric."
    },
    {
      id: 3,
      name: "Leather Handbag",
      brand: "LuxBags",
      gender: "female",
      category: "Bags",
      size: "One Size",
      color: "Brown",
      price: 129.99,
      is_in_inventory: true,
      items_left: 30,
      imageURL: "https://images.unsplash.com/photo-1514996937319-344454492b37?auto=format&fit=crop&w=500&q=80",
      slug: "leather-handbag",
      description: "Elegant brown leather handbag with ample storage and a chic design."
    },
    {
      id: 4,
      name: "Running Sneakers",
      brand: "Speedster",
      gender: "unisex",
      category: "Shoes",
      size: "10",
      color: "Black",
      price: 89.99,
      is_in_inventory: false,
      items_left: 0,
      imageURL: "https://images.unsplash.com/photo-1528701800489-1a8d0dcb96a1?auto=format&fit=crop&w=500&q=80",
      slug: "running-sneakers",
      description: "Lightweight and comfortable running sneakers designed for all terrains."
    },
    {
      id: 5,
      name: "Formal Shirt",
      brand: "SuitUp",
      gender: "male",
      category: "Shirts",
      size: "L",
      color: "Light Blue",
      price: 39.99,
      is_in_inventory: true,
      items_left: 40,
      imageURL: "https://images.unsplash.com/photo-1521334884684-d80222895322?auto=format&fit=crop&w=500&q=80",
      slug: "formal-shirt",
      description: "Light blue formal shirt tailored for a sharp, professional look."
    },
    {
      id: 6,
      name: "Yoga Leggings",
      brand: "FlexFit",
      gender: "female",
      category: "Leggings",
      size: "S",
      color: "Gray",
      price: 29.99,
      is_in_inventory: true,
      items_left: 70,
      imageURL: "https://images.unsplash.com/photo-1598970434795-0c54fe7c0642?auto=format&fit=crop&w=500&q=80",
      slug: "yoga-leggings",
      description: "Stretchy and breathable gray leggings, perfect for yoga and workouts."
    },
    {
      id: 7,
      name: "Denim Jacket",
      brand: "DenimPro",
      gender: "unisex",
      category: "Jackets",
      size: "M",
      color: "Blue",
      price: 69.99,
      is_in_inventory: true,
      items_left: 25,
      imageURL: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=500&q=80",
      slug: "denim-jacket",
      description: "Classic blue denim jacket with a comfortable fit and durable stitching."
    },
    {
      id: 8,
      name: "Casual Hoodie",
      brand: "CozyWear",
      gender: "male",
      category: "Hoodies",
      size: "XL",
      color: "Navy",
      price: 49.99,
      is_in_inventory: true,
      items_left: 60,
      imageURL: "https://images.unsplash.com/photo-1495121605193-b116b5b09a96?auto=format&fit=crop&w=500&q=80",
      slug: "casual-hoodie",
      description: "Comfortable navy hoodie for casual wear and relaxed days."
    },
    {
      id: 9,
      name: "Summer Dress",
      brand: "Sunshine",
      gender: "female",
      category: "Dresses",
      size: "M",
      color: "Yellow",
      price: 59.99,
      is_in_inventory: true,
      items_left: 20,
      imageURL: "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=500&q=80",
      slug: "summer-dress",
      description: "Bright yellow summer dress designed for comfort and style in warm weather."
    },
    {
      id: 10,
      name: "Sports Watch",
      brand: "ChronoX",
      gender: "unisex",
      category: "Accessories",
      size: "One Size",
      color: "Black",
      price: 199.99,
      is_in_inventory: true,
      items_left: 15,
      imageURL: "https://images.unsplash.com/photo-1519744792095-2f2205e87b6f?auto=format&fit=crop&w=500&q=80",
      slug: "sports-watch",
      description: "Durable sports watch with multiple features for athletes and outdoor lovers."
    },
    {
      id: 11,
      name: "Graphic Tee",
      brand: "UrbanStyle",
      gender: "male",
      category: "T-Shirts",
      size: "L",
      color: "Black",
      price: 24.99,
      is_in_inventory: true,
      items_left: 80,
      imageURL: "https://images.unsplash.com/photo-1520975911724-99a206158e0d?auto=format&fit=crop&w=500&q=80",
      slug: "graphic-tee",
      description: "Trendy black graphic tee featuring urban designs for everyday style."
    },
    {
      id: 12,
      name: "Leather Boots",
      brand: "BootCraft",
      gender: "female",
      category: "Shoes",
      size: "8",
      color: "Dark Brown",
      price: 139.99,
      is_in_inventory: false,
      items_left: 0,
      imageURL: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=500&q=80",
      slug: "leather-boots",
      description: "Stylish dark brown leather boots built for both fashion and durability."
    },
    {
      id: 13,
      name: "Winter Coat",
      brand: "ColdShield",
      gender: "unisex",
      category: "Coats",
      size: "XL",
      color: "Gray",
      price: 159.99,
      is_in_inventory: true,
      items_left: 10,
      imageURL: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=500&q=80",
      slug: "winter-coat",
      description: "Warm gray winter coat designed to keep you cozy in cold conditions."
    },
    {
      id: 14,
      name: "Baseball Cap",
      brand: "HeadGear",
      gender: "unisex",
      category: "Accessories",
      size: "One Size",
      color: "Red",
      price: 14.99,
      is_in_inventory: true,
      items_left: 100,
      imageURL: "https://images.unsplash.com/photo-1505236731531-1c4e1de3f61d?auto=format&fit=crop&w=500&q=80",
      slug: "baseball-cap",
      description: "Classic red baseball cap for sun protection and casual style."
    },
    {
      id: 15,
      name: "Chino Pants",
      brand: "CasualLine",
      gender: "male",
      category: "Pants",
      size: "34",
      color: "Khaki",
      price: 44.99,
      is_in_inventory: true,
      items_left: 45,
      imageURL: "https://images.unsplash.com/photo-1516684669134-b8f9e1a8692b?auto=format&fit=crop&w=500&q=80",
      slug: "chino-pants",
      description: "Versatile khaki chinos with a comfortable fit for casual and semi-formal wear."
    },
    {
      id: 16,
      name: "Floral Skirt",
      brand: "Bloom",
      gender: "female",
      category: "Skirts",
      size: "S",
      color: "Pink",
      price: 39.99,
      is_in_inventory: true,
      items_left: 35,
      imageURL: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=500&q=80",
      slug: "floral-skirt",
      description: "Soft pink floral skirt ideal for spring outings and casual gatherings."
    },
    {
      id: 17,
      name: "Graphic Hoodie",
      brand: "UrbanStyle",
      gender: "unisex",
      category: "Hoodies",
      size: "M",
      color: "Gray",
      price: 54.99,
      is_in_inventory: true,
      items_left: 40,
      imageURL: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=500&q=80",
      slug: "graphic-hoodie",
      description: "Comfortable gray hoodie with bold graphic designs for an urban look."
    },
    {
      id: 18,
      name: "Trail Running Shoes",
      brand: "Speedster",
      gender: "male",
      category: "Shoes",
      size: "11",
      color: "Blue",
      price: 99.99,
      is_in_inventory: true,
      items_left: 22,
      imageURL: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=500&q=80",
      slug: "trail-running-shoes",
      description: "Durable blue trail shoes designed for rugged terrain and long runs."
    },
    {
      id: 19,
      name: "Silk Scarf",
      brand: "LuxBags",
      gender: "female",
      category: "Accessories",
      size: "One Size",
      color: "Red",
      price: 25.99,
      is_in_inventory: true,
      items_left: 75,
      imageURL: "https://images.unsplash.com/photo-1505843754303-9a3e492d1314?auto=format&fit=crop&w=500&q=80",
      slug: "silk-scarf",
      description: "Elegant red silk scarf to add a pop of color to any outfit."
    },
    {
      id: 20,
      name: "Cargo Shorts",
      brand: "CasualLine",
      gender: "male",
      category: "Shorts",
      size: "32",
      color: "Green",
      price: 29.99,
      is_in_inventory: true,
      items_left: 65,
      imageURL: "https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=500&q=80",
      slug: "cargo-shorts",
      description: "Practical green cargo shorts with multiple pockets for utility and style."
    },
    {
      id: 21,
      name: "V-Neck Sweater",
      brand: "CozyWear",
      gender: "unisex",
      category: "Sweaters",
      size: "L",
      color: "Burgundy",
      price: 44.99,
      is_in_inventory: true,
      items_left: 50,
      imageURL: "https://images.unsplash.com/photo-1520975911724-99a206158e0d?auto=format&fit=crop&w=500&q=80",
      slug: "v-neck-sweater",
      description: "Soft burgundy v-neck sweater suitable for layering or standalone wear."
    },
    {
      id: 22,
      name: "Leather Belt",
      brand: "BootCraft",
      gender: "male",
      category: "Accessories",
      size: "One Size",
      color: "Black",
      price: 19.99,
      is_in_inventory: true,
      items_left: 90,
      imageURL: "https://images.unsplash.com/photo-1519744792095-2f2205e87b6f?auto=format&fit=crop&w=500&q=80",
      slug: "leather-belt",
      description: "Classic black leather belt crafted for durability and style."
    },
    {
      id: 23,
      name: "Denim Shorts",
      brand: "DenimPro",
      gender: "female",
      category: "Shorts",
      size: "M",
      color: "Blue",
      price: 34.99,
      is_in_inventory: true,
      items_left: 70,
      imageURL: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=500&q=80",
      slug: "denim-shorts",
      description: "Comfortable blue denim shorts, perfect for casual summer days."
    },
    {
      id: 24,
      name: "Button-Up Shirt",
      brand: "SuitUp",
      gender: "male",
      category: "Shirts",
      size: "M",
      color: "White",
      price: 39.99,
      is_in_inventory: true,
      items_left: 60,
      imageURL: "https://images.unsplash.com/photo-1521334884684-d80222895322?auto=format&fit=crop&w=500&q=80",
      slug: "button-up-shirt",
      description: "Crisp white button-up shirt, a staple for formal and business wear."
    },
    {
      id: 25,
      name: "Plaid Skirt",
      brand: "Bloom",
      gender: "female",
      category: "Skirts",
      size: "M",
      color: "Red",
      price: 44.99,
      is_in_inventory: true,
      items_left: 45,
      imageURL: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=500&q=80",
      slug: "plaid-skirt",
      description: "Chic red plaid skirt, perfect for casual and semi-formal occasions."
    },
    {
      id: 26,
      name: "Running Shorts",
      brand: "Speedster",
      gender: "male",
      category: "Shorts",
      size: "L",
      color: "Black",
      price: 29.99,
      is_in_inventory: true,
      items_left: 55,
      imageURL: "https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=500&q=80",
      slug: "running-shorts",
      description: "Black running shorts designed for comfort and breathability."
    }
  ];

}
